CREATE TABLE APP.RECIPE
(ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
 NAME VARCHAR(25),
 DESCRIPTION VARCHAR(25),
 INSTRUCTIONS VARCHAR(25),
 PRIMARY KEY (ID));

CREATE TABLE APP.INGREDIENT
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    RECIPE_ID INTEGER NOT NULL,
    NAME VARCHAR(25),
    IMAGE VARCHAR(25),
    CONSISTENCY VARCHAR(25),
    NAMECLEAN VARCHAR(25),
    ORIGINAL VARCHAR(25),
    ORIGINALSTRING VARCHAR(25),
    AMOUNT DOUBLE,
    UNIT VARCHAR(25),
    META VARCHAR(25),
    METAINFORMATION VARCHAR(25),
    MEASURES VARCHAR(25),
    PRIMARY KEY (ID,RECIPE_ID));

